In [2]:
x = []
y = [1,2,3,4,5,6,8]
for a in y:
    x.append(a*8)
print(x)


[8, 16, 24, 32, 40, 48, 64]


In [14]:
import numpy as np
x = np.arange(7)
print(x)
multiple = [a for a in x if a % 2 == 0 ]
print(multiple)

[0 1 2 3 4 5 6]
[0, 2, 4, 6]


In [23]:
dict = {'new':'car','old':'house','bad':'dog'}
for a in dict:
    print(a+':'+dict[a])
    print()
    

new:car

old:house

bad:dog



In [22]:
for k,v in dict.items():
    print(k,v)

new car
old house
bad dog


In [31]:
list = range(7)
odd = {x:x**2 for x in list if x%2 == 1 }
odd
complex(1,2)


(1+2j)

In [44]:
class mulComplex:
    def __init__(self,comp1):
        self.comp1 = comp1
        #self.comp2 = comp2
    def multi(self,comp):
        comp3 = self.comp1*comp
        print(comp3)
        
    
    
comp1 = complex(1,2)
comp2 = complex(3,4)
a = mulComplex(comp1)
a.multi(comp2)


(-5+10j)


In [49]:
###2nd method
class mulcomplex:
    def __init__(self,a,b):
        self.comp1 = complex(a,b)
    def add(self,b):
        c = self.comp1 + b.comp1
        return c
        

        
a = mulcomplex(2,3)
b = mulcomplex(3,5)
c = a.add(b)
print(c)


(5+8j)


In [55]:
#making own complex class
class complex:
    def __init__(self,a,b):
        self.real = a
        self.img = b
    def add(self,comp):
        return complex(self.real+comp.real,self.img+comp.img)
    def __str__(self):
        return str((self.real,self.img))
a = complex(2,3)
b = complex(3,5)
c = a.add(b)
print(c)

(5, 8)


# NUMPY

In [56]:
a = np.arange(6)
a.shape

(6,)

In [58]:
a = np.array([[1,2,3,4],[2,3,4,5]])
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [75]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print(a[[0,1,1],[0,1,0]])

[[1 2]
 [3 4]
 [5 6]]
[1 4 3]


In [68]:
a = np.arange(12)
b = a.reshape(3,4)
c = b[1:,1::2]
print(b)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 5  7]
 [ 9 11]]


In [79]:
a = np.arange(12)
a = a.reshape(4,3)
b = np.array([0,2,0,1])
print(a)
print(a[np.arange(4),b])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  5  6 10]


In [82]:
a[np.arange(4),b] +=10
boolindex = (a>2)
boolindex

array([[ True, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)